name: Generate PDF Documentation
run-name: ${{github.actor}} generating refman.pdf

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy-pdf-doc:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ""

      - name: Cache apt pdf doc install
        id: cache-apt
        uses: actions/cache@v4
        env:
          cache-name: cache-apt-pdf-doc-install
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-pdf-doc-install-${{ env.cache-name }}-${{ hashFiles('**/compile.sh') }}
          restore-keys: |
            ${{ runner.os }}-apt-pdf-doc-install-${{ env.cache-name }}-

      # - name: Cache cmake build doc pdf
      #   id: cache-cmake
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-cmake-build-doc-pdf
      #   with:
      #     path: ./build
      #     key: ${{ runner.os }}-build-doc-pdf-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-doc-pdf-${{ env.cache-name }}-

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen texlive-full texlive-latex-base texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-all
          version: 1.0

      - name: Configure CMake and Build Documentation
        run: |
          cmake -S . -B build -DBUILD_DOC=ON
          cmake --build build --target doc_doxygen

      - name: Push refman.pdf
        id: git-check-refman
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.git-check-refman.outputs.modified == 'true'
        with:
          commit_message: Automated Change