name: Mirror Repository
run-name: ${{github.actor}} verifying my code

on:
  workflow_run:
    workflows: ["Test Environment"]
    types:
      - completed
  workflow_dispatch:

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: # <-- use 'secrets' to pass credential information.
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
