name: Test Environment
run-name: ${{github.actor}} verifying my code

on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

jobs:
  linux_install:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          repository: ""

      - name: Setup environment
        run: ./compile.sh
