name: Test Environment
run-name: ${{github.actor}} verifying my code

on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

jobs:
  linux_install:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          repository: ""

      - name: Cache apt install
        id: cache-apt
        uses: actions/cache@v4
        env:
          cache-name: cache-apt-install
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-install-${{ env.cache-name }}-${{ hashFiles('**/compile.sh') }}
          restore-keys: |
            ${{ runner.os }}-install-${{ env.cache-name }}-

      - name: compile project
        run: cmake -S . -B build # do apt install

      - name: Cache cmake build
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-build
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: build project
        run: cmake --build build -j "$(nproc)"

  windows_install:
    runs-on: windows-latest
    timeout-minutes: 20
    if : github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'windows'
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          repository: ""
      - name: Cache vcpkg Install
        id: cache-vcpkg
        uses: actions/cache@v4
        env:
          cache-name: cache-vcpkg-install
        with:
          path: C:/vcpkg
          key: ${{ runner.os }}-vcpkg-install-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-install-${{ env.cache-name }}-
      - name: Cache cmake build
        id: cache-cmake
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-build
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: compile project
        run: cmake -S . -B build
      - name: build project
        run: cmake --build build -- /maxcpucount:4  /p:VcpkgEnableManifest=true

  push_to_mirror:
    timeout-minutes: 10
    needs: [linux_install]
    runs-on: ubuntu-latest
    if: github.repository == 'AleaChlodnik/R-Type'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: # <-- use 'secrets' to pass credential information.
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
